name: Build and Push Flatpak manifest

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'readme.md'
  workflow_dispatch:
  repository_dispatch:
    types: [flatpak-publish]

env:
  MANIFEST: org.cataclysmdda.CataclysmDDA.experimental.yml

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [ x86_64, aarch64 ]
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-22.04-arm' || 'ubuntu-latest' }}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Import GPG-key
        id: gpg-key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: ${{ env.MANIFEST }}
          gpg-sign: ${{ steps.gpg-key.outputs.fingerprint }}
          build-bundle: false
          upload-artifact: false
          arch: ${{ matrix.arch }}

      - name: Upload repo ${{ matrix.arch }}
        uses: actions/upload-artifact@v4
        with:
          name: repo-${{ matrix.arch }}
          path: repo


  publish:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    permissions:
      contents: write

    steps:
      - name: Import GPG-key
        id: gpg-key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Prepare GPG-pubkey
        run: |
          gpg --export ${{ steps.gpg-key.outputs.fingerprint }} > pubkey.gpg

      - name: Download all repos
        uses: actions/download-artifact@v4
        with:
          pattern: repo-*
          path: repos

      - name: Merge repos into one
        run: |
          mkdir repo
          ostree --repo=./repo init --mode=archive-z2
          for ref in ./repos/repo-*/repo; do
            ostree pull-local $ref --repo=./repo
          done
          flatpak build-update-repo \
            --gpg-sign=${{ steps.gpg-key.outputs.fingerprint }} \
            --gpg-import=pubkey.gpg \
            --generate-static-deltas \
            ./repo

      - name: Set the root of the repository
        run: |
          mkdir ./root
          mv ./repo ./root
          touch ./root/.nojekyll

      - name: Write .flatpakrepo file
        env:
          PAGES_REPO_URL: ${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
        run: |
          cat > ./root/${{ github.repository_owner }}.flatpakrepo << EOF 
          [Flatpak Repo]
          Title=$PAGES_REPO_URL
          Url=https://$PAGES_REPO_URL/repo/
          GPGKey=$(cat pubkey.gpg | base64 --wrap=0)
          EOF

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./root
          force_orphan: true
